service: serverless-calculate-bmi-ecoronel45

provider:
  name: google
  stage: dev
  runtime: python39
  region: us-central1
  project: milab-utp
  credentials: gcloud/secrets.json
 
frameworkVersion: '3'
plugins:
  - serverless-google-cloudfunctions
  - serverless-prune-plugin

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - gcloud/**
    - .github/**

functions:
  calculate_bmi:
    handler: calculate_bmi
    events:
      - http: true
